import {
  app,
  autoUpdater,
  BrowserWindow,
  globalShortcut,
  Menu,
  nativeImage,
  screen,
  shell,
  Tray,
} from 'electron';
import { randomUUID } from 'node:crypto';
import path from 'node:path';

import type { DesktopCommand } from './main/agent/execution-contracts';
import {
  TaskExecutionCoordinator,
  type DesktopPresentation,
} from './main/agent/execution-coordinator';
import { registerGlobalGuidanceShortcuts } from './main/agent/global-guidance-shortcuts';
import { registerGlobalTaskCancelShortcut } from './main/agent/global-task-cancel-shortcut';
import {
  MACOS_VISION_OCR_HELPER_NAME,
  MacOSVisionGrounder,
} from './main/agent/macos-vision-grounder';
import { GptResponsesPlanner } from './main/agent/responses-planner';
import { GptTaskIntentCompiler } from './main/agent/task-intent-compiler';
import { TaskRuntime } from './main/agent/task-runtime';
import { TaskSubmissionService } from './main/agent/task-submission-service';
import { FileAnalyticsIdentityStore } from './main/analytics/analytics-identity-store';
import { AnalyticsService } from './main/analytics/analytics-service';
import { EncryptedAuthSessionStore } from './main/auth/auth-session-store';
import { GoogleAuthService } from './main/auth/google-auth-service';
import { LocalOAuthBrowserFlow } from './main/auth/local-oauth-browser-flow';
import { keepWindowAliveForBackgroundVoice } from './main/background-app-lifecycle';
import {
  getVirtualDisplayBounds,
  interpolateCompanionPosition,
  placeCompanionForBrowserNavigation,
  placeCompanionNearCursor,
  placeGuidanceCallout,
  shouldUseCompanionOverlay,
  type Point,
  type Rectangle,
} from './main/companion/companion-position';
import { CuaService } from './main/cua/cua-service';
import { TaskHistoryService } from './main/history/task-history-service';
import { PostgresTaskHistoryStore } from './main/history/task-history-store';
import { registerIpcHandlers } from './main/ipc/register-ipc';
import { EncryptedMembershipActivationStore } from './main/membership/membership-activation-store';
import { MembershipService } from './main/membership/membership-service';
import {
  AppPreferencesService,
  FileAppPreferencesStore,
} from './main/preferences/app-preferences-service';
import { registerScreenRecordingHost } from './main/screen-recording-registration';
import {
  initializeSingleInstance,
  isolateDevelopmentInstance,
} from './main/single-instance';
import { systemPermissionSettingsUrl } from './main/system-permission-settings';
import { AppUpdateService } from './main/update/app-update-service';
import { ElevenLabsTtsService } from './main/voice/elevenlabs-tts-service';
import { registerGlobalVoiceShortcut } from './main/voice/global-voice-shortcut';
import {
  MACOS_VOICE_SHORTCUT_HELPER_NAME,
  watchMacOSGlobalVoiceShortcut,
} from './main/voice/macos-voice-shortcut-watcher';
import { EncryptedVoiceCredentialStore } from './main/voice/voice-credential-store';
import { VoiceService } from './main/voice/voice-service';
import {
  CompanionGuidanceSchema,
  CompanionSpeechSchema,
  TaskUpdateSchema,
  type AuthUser,
  type CompanionGuidance,
  type CompanionSpeech,
  type CompanionState,
  type TaskSnapshot,
} from './shared/contracts';
import { IPC_CHANNELS } from './shared/desktop-api';
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
// eslint-disable-next-line @typescript-eslint/no-require-imports
if (require('electron-squirrel-startup')) {
  app.quit();
}

app.setName('TroCode');
isolateDevelopmentInstance(app);

const hasSingleInstanceLock = initializeSingleInstance(app, () => {
  if (isShuttingDown) return;

  const window = mainWindow;
  if (window && !window.isDestroyed()) {
    revealWindow(window);
    return;
  }

  if (app.isReady()) {
    createWindow();
    createCompanionWindow();
    createGuidanceWindow();
  }
});

const taskRuntime = new TaskRuntime();
const databaseUrl = process.env.DATABASE_URL?.trim() ?? '';
const taskHistoryService = new TaskHistoryService({
  onError: (error) => {
    console.error('[task-history] PostgreSQL persistence failed.', error);
  },
  store: databaseUrl ? new PostgresTaskHistoryStore(databaseUrl) : null,
});
taskRuntime.on('task-update', taskHistoryService.recordTaskUpdate);
const oauthBrowserFlow = new LocalOAuthBrowserFlow({
  openExternal: async (url) => shell.openExternal(url, { activate: true }),
});
const authService = new GoogleAuthService({
  browserFlow: oauthBrowserFlow,
  clientId: process.env.GOOGLE_OAUTH_CLIENT_ID,
  clientSecret: process.env.GOOGLE_OAUTH_CLIENT_SECRET,
  sessionStore: new EncryptedAuthSessionStore(),
});
const membershipService = new MembershipService({
  publicKey: process.env.TROCODE_MEMBERSHIP_PUBLIC_KEY,
  required: app.isPackaged,
  store: new EncryptedMembershipActivationStore(),
});
const cuaService = new CuaService();
const appPreferencesService = new AppPreferencesService(
  new FileAppPreferencesStore(
    path.join(app.getPath('userData'), 'app-preferences.json'),
  ),
);
const voiceCredentialStore = new EncryptedVoiceCredentialStore();
const voiceService = new VoiceService({
  credentialStore: voiceCredentialStore,
  preferencesService: appPreferencesService,
});
const elevenLabsTtsService = new ElevenLabsTtsService();
const responsesPlanner = new GptResponsesPlanner({
  credentialStore: voiceCredentialStore,
});
const taskIntentCompiler = new GptTaskIntentCompiler({
  credentialStore: voiceCredentialStore,
});
const taskSubmissionService = new TaskSubmissionService({
  compiler: taskIntentCompiler,
  runtime: taskRuntime,
});
const visionGrounder = new MacOSVisionGrounder({
  executablePath: macOSVisionOcrHelperPath(),
});
const executionCoordinator = new TaskExecutionCoordinator({
  cua: cuaService,
  dismissPresentation: dismissCompanionGuidance,
  onGuidancePlaybackChange: (_taskId, paused) =>
    updateGuidancePlaybackState(paused),
  planner: responsesPlanner,
  pointGrounder: (decision, observation, signal) =>
    visionGrounder.ground(decision, observation, signal),
  runtime: taskRuntime,
  openExternal: async (url) => shell.openExternal(url, { activate: true }),
  prepareDesktop: async () => {
    const window = mainWindow;
    if (window && !window.isDestroyed() && window.isVisible()) window.hide();

    const restoreCompanion = Boolean(
      companionWindow &&
        !companionWindow.isDestroyed() &&
        companionWindow.isVisible(),
    );
    if (restoreCompanion) companionWindow?.hide();
    if (guidanceWindow && !guidanceWindow.isDestroyed()) guidanceWindow.hide();
    await new Promise<void>((resolve) => setTimeout(resolve, 120));

    return () => {
      if (
        restoreCompanion &&
        companionWindow &&
        !companionWindow.isDestroyed()
      ) {
        companionWindow.showInactive();
      }
    };
  },
  presentAction: presentCompanionAction,
});
const appUpdateService = new AppUpdateService({
  architecture: process.arch,
  currentVersion: app.getVersion(),
  isPackaged: app.isPackaged,
  platform: process.platform,
  prepareToInstall: prepareForUpdateInstall,
  repository: 'ducnguyen67201/TroCode',
  updater: autoUpdater,
});
const COMPANION_SIZE = { height: 44, width: 44 } as const;
const COMPANION_GAP = 8;
const COMPANION_GLIDE_DURATION_MS = 360;
const COMPANION_FOLLOW_INTERVAL_MS = 16;
const GUIDANCE_CALLOUT_SIZE = { height: 176, width: 380 } as const;
const SHUTDOWN_GRACE_PERIOD_MS = 2_000;

interface CompanionGlide {
  abortListener: () => void;
  from: Point;
  reject: (error: Error) => void;
  resolve: () => void;
  signal: AbortSignal;
  startedAt: number;
  to: Point;
}

let mainWindow: BrowserWindow | null = null;
let companionWindow: BrowserWindow | null = null;
let guidanceWindow: BrowserWindow | null = null;
let analyticsService: AnalyticsService | null = null;
let companionState: CompanionState = 'idle';
let companionFollowTimer: ReturnType<typeof setInterval> | null = null;
let companionGlide: CompanionGlide | null = null;
let companionPinnedPosition: Point | null = null;
let activeCompanionGuidance: CompanionGuidance | null = null;
let activeCompanionSpeech: CompanionSpeech | null = null;
let companionGuidancePreviousState: CompanionState | null = null;
let guidancePlaybackPaused = false;
let guidanceSpeechController: AbortController | null = null;
let lastCompanionPosition: Point | null = null;
let forcedExitTimer: ReturnType<typeof setTimeout> | null = null;
let shutdownPromise: Promise<void> | null = null;
let unregisterIpcHandlers: (() => void) | null = null;
let unregisterGlobalGuidanceShortcuts: (() => void) | null = null;
let unregisterGlobalTaskCancelShortcut: (() => void) | null = null;
let unregisterGlobalVoiceShortcut: (() => void) | null = null;
let removeMainWindowCloseBehavior: (() => void) | null = null;
let backgroundTray: Tray | null = null;
let isShuttingDown = false;

function stopCompanionFollowing(): void {
  if (companionFollowTimer) clearInterval(companionFollowTimer);
  companionFollowTimer = null;
  cancelCompanionGlide(isShuttingDown ? createAbortError() : undefined);
  companionPinnedPosition = null;
  lastCompanionPosition = null;
}

function sendCompanionState(): void {
  if (!companionWindow || companionWindow.isDestroyed()) return;
  companionWindow.webContents.send(
    IPC_CHANNELS.companionStateChanged,
    companionState,
  );
}

function updateCompanionState(state: CompanionState): void {
  companionState = state;
  sendCompanionState();
}

function boundsEqual(left: Rectangle, right: Rectangle): boolean {
  return (
    left.x === right.x &&
    left.y === right.y &&
    left.width === right.width &&
    left.height === right.height
  );
}

function pointEqual(left: Point | null, right: Point): boolean {
  return left?.x === right.x && left.y === right.y;
}

function getCompanionOverlayBounds(): Rectangle {
  return getVirtualDisplayBounds(
    screen.getAllDisplays().map((display) => display.bounds),
  );
}

function sendCompanionPosition(position: Point): void {
  if (!companionWindow || companionWindow.isDestroyed()) return;
  if (pointEqual(lastCompanionPosition, position)) return;

  lastCompanionPosition = position;
  companionWindow.webContents.send(
    IPC_CHANNELS.companionPositionChanged,
    position,
  );
}

function createAbortError(): Error {
  const error = new Error('Companion movement was cancelled.');
  error.name = 'AbortError';
  return error;
}

function settleCompanionGlide(error?: Error): void {
  const glide = companionGlide;
  if (!glide) return;

  companionGlide = null;
  glide.signal.removeEventListener('abort', glide.abortListener);
  if (error) {
    companionPinnedPosition = null;
    glide.reject(error);
    return;
  }

  companionPinnedPosition = glide.to;
  glide.resolve();
}

function cancelCompanionGlide(error?: Error): void {
  settleCompanionGlide(error);
}

function resetCompanionPresentation(): void {
  cancelCompanionGlide();
  companionPinnedPosition = null;
  dismissCompanionGuidance();
  positionCompanion();
}

function sendCompanionGuidance(): void {
  if (!guidanceWindow || guidanceWindow.isDestroyed()) return;
  guidanceWindow.webContents.send(
    IPC_CHANNELS.companionGuidanceChanged,
    activeCompanionGuidance,
  );
}

function sendCompanionSpeech(): void {
  if (!guidanceWindow || guidanceWindow.isDestroyed()) return;
  guidanceWindow.webContents.send(
    IPC_CHANNELS.companionSpeechChanged,
    activeCompanionSpeech,
  );
}

function stopGuidanceSpeech(): void {
  guidanceSpeechController?.abort();
  guidanceSpeechController = null;
  activeCompanionSpeech = null;
  sendCompanionSpeech();
}

function startGuidanceSpeech(message: string, signal: AbortSignal): void {
  stopGuidanceSpeech();
  if (!elevenLabsTtsService.isConfigured()) return;

  const controller = new AbortController();
  const handleTaskAbort = (): void => controller.abort(signal.reason);
  signal.addEventListener('abort', handleTaskAbort, { once: true });
  guidanceSpeechController = controller;

  void elevenLabsTtsService
    .synthesize(message, controller.signal)
    .then((speech) => {
      if (
        !speech ||
        controller.signal.aborted ||
        guidanceSpeechController !== controller
      ) {
        return;
      }
      activeCompanionSpeech = CompanionSpeechSchema.parse({
        id: randomUUID(),
        ...speech,
      });
      sendCompanionSpeech();
    })
    .catch((error: unknown) => {
      if (controller.signal.aborted) return;
      console.warn('[voice:tts] companion speech unavailable', {
        error: error instanceof Error ? error.message.slice(0, 300) : 'Unknown error',
      });
    })
    .finally(() => {
      signal.removeEventListener('abort', handleTaskAbort);
      if (guidanceSpeechController === controller) {
        guidanceSpeechController = null;
      }
    });
}

function hideGuidanceCallout(): void {
  stopGuidanceSpeech();
  activeCompanionGuidance = null;
  sendCompanionGuidance();
  if (guidanceWindow && !guidanceWindow.isDestroyed()) guidanceWindow.hide();
}

function dismissCompanionGuidance(): void {
  hideGuidanceCallout();
  if (
    companionGuidancePreviousState !== null &&
    companionState === 'guiding'
  ) {
    updateCompanionState(companionGuidancePreviousState);
  }
  companionGuidancePreviousState = null;
}

function updateGuidancePlaybackState(paused: boolean): void {
  guidancePlaybackPaused = paused;
  if (!activeCompanionGuidance) return;
  activeCompanionGuidance = CompanionGuidanceSchema.parse({
    ...activeCompanionGuidance,
    playback: paused ? 'paused' : 'playing',
  });
  sendCompanionGuidance();
}

function showGuidanceCallout(
  target: Point,
  presentation: DesktopPresentation,
): void {
  if (!presentation.message) return;
  if (!guidanceWindow || guidanceWindow.isDestroyed()) {
    createGuidanceWindow();
  }
  if (!guidanceWindow || guidanceWindow.isDestroyed()) return;

  const display = screen.getDisplayNearestPoint(target);
  const position = placeGuidanceCallout(
    target,
    display.bounds,
    GUIDANCE_CALLOUT_SIZE,
    COMPANION_SIZE,
  );
  activeCompanionGuidance = CompanionGuidanceSchema.parse({
    message: presentation.message.slice(0, 240),
    playback: guidancePlaybackPaused ? 'paused' : 'playing',
    side: position.x < target.x ? 'left' : 'right',
    ...(presentation.target
      ? { target: presentation.target.slice(0, 80) }
      : {}),
  });
  guidanceWindow.setBounds({ ...position, ...GUIDANCE_CALLOUT_SIZE }, false);
  sendCompanionGuidance();
  guidanceWindow.showInactive();
}

function companionTargetForCommand(
  command: DesktopCommand,
  presentation?: DesktopPresentation,
): Point | null {
  if (command.kind === 'open_url') {
    const cursor = screen.getCursorScreenPoint();
    const display = screen.getDisplayNearestPoint(cursor);
    return placeCompanionForBrowserNavigation(
      display.workArea,
      COMPANION_SIZE,
      COMPANION_GAP,
    );
  }

  if (
    command.kind !== 'click' &&
    command.kind !== 'point' &&
    command.kind !== 'scroll'
  ) {
    return null;
  }
  const pointerPosition = presentation?.screenPoint ?? {
    x: command.x,
    y: command.y,
  };
  const display = screen.getDisplayNearestPoint(pointerPosition);
  return placeCompanionNearCursor(
    pointerPosition,
    display.bounds,
    COMPANION_SIZE,
    COMPANION_GAP,
  );
}

async function presentCompanionAction(
  command: DesktopCommand,
  signal: AbortSignal,
  presentation?: DesktopPresentation,
): Promise<void> {
  const isGuidancePoint = command.kind === 'point';
  const previousCompanionState = companionState;
  const to = companionTargetForCommand(command, presentation);
  if (!to || !companionWindow || companionWindow.isDestroyed()) {
    return;
  }
  if (command.kind === 'point') {
    console.info(
      '[companion] point.presentation',
      JSON.stringify({
        cuaScreenshotPoint: { x: command.x, y: command.y },
        overlayScreenPoint: presentation?.screenPoint ?? null,
        companionWindowPosition: to,
      }),
    );
  }
  if (signal.aborted) throw createAbortError();
  if (isGuidancePoint) {
    if (companionGuidancePreviousState === null) {
      companionGuidancePreviousState = previousCompanionState;
    }
    updateCompanionState('guiding');
  }

  const from = getCurrentCompanionScreenPosition();
  if (pointEqual(from, to)) {
    companionPinnedPosition = to;
    positionCompanion();
    if (isGuidancePoint) {
      showGuidancePresentation(command, presentation, signal);
    }
    return;
  }

  cancelCompanionGlide();
  await new Promise<void>((resolve, reject) => {
    const abortListener = (): void => settleCompanionGlide(createAbortError());
    companionGlide = {
      abortListener,
      from,
      reject,
      resolve,
      signal,
      startedAt: Date.now(),
      to,
    };
    signal.addEventListener('abort', abortListener, { once: true });
    positionCompanion();
  });

  if (isGuidancePoint) {
    showGuidancePresentation(command, presentation, signal);
  }
}

function showGuidancePresentation(
  command: Extract<DesktopCommand, { kind: 'point' }>,
  presentation: DesktopPresentation | undefined,
  signal: AbortSignal,
): void {
  if (presentation?.message) {
    showGuidanceCallout(
      presentation.screenPoint ?? { x: command.x, y: command.y },
      presentation,
    );
    startGuidanceSpeech(presentation.message, signal);
  }
}

async function identifyAnalyticsUser(user: AuthUser): Promise<void> {
  taskHistoryService.setCurrentOwner(user.id);
  await analyticsService?.identifyUser({
    email: user.email,
    loginMethod: 'oauth',
    name: user.name,
    userId: user.id,
  });
}

function finishShutdown(exitCode: number): void {
  if (forcedExitTimer) clearTimeout(forcedExitTimer);
  forcedExitTimer = null;
  app.exit(exitCode);
}

function prepareApplicationShutdown(): Promise<void> {
  if (shutdownPromise) return shutdownPromise;

  isShuttingDown = true;
  stopCompanionFollowing();
  unregisterGlobalGuidanceShortcuts?.();
  unregisterGlobalGuidanceShortcuts = null;
  unregisterGlobalTaskCancelShortcut?.();
  unregisterGlobalTaskCancelShortcut = null;
  unregisterGlobalVoiceShortcut?.();
  unregisterGlobalVoiceShortcut = null;
  backgroundTray?.destroy();
  backgroundTray = null;
  oauthBrowserFlow.shutdown();
  unregisterIpcHandlers?.();
  unregisterIpcHandlers = null;
  taskRuntime.off('task-update', trackTaskAnalytics);

  if (mainWindow && !mainWindow.isDestroyed()) mainWindow.hide();
  if (companionWindow && !companionWindow.isDestroyed()) companionWindow.hide();
  if (guidanceWindow && !guidanceWindow.isDestroyed()) guidanceWindow.hide();

  const analyticsShutdown = analyticsService?.shutdown() ?? Promise.resolve();
  const executionShutdown = executionCoordinator.shutdown().finally(() =>
    Promise.allSettled([
      cuaService.shutdown(),
      taskHistoryService.shutdown(),
    ]),
  );
  shutdownPromise = Promise.allSettled([
    executionShutdown,
    analyticsShutdown,
  ]).then(() => undefined);
  return shutdownPromise;
}

async function prepareForUpdateInstall(): Promise<void> {
  const applicationShutdown = prepareApplicationShutdown();
  await new Promise<void>((resolve) => {
    const graceTimer = setTimeout(resolve, SHUTDOWN_GRACE_PERIOD_MS);
    graceTimer.unref?.();
    void applicationShutdown.finally(() => {
      clearTimeout(graceTimer);
      resolve();
    });
  });
}

function beginShutdown(exitCode = 0): void {
  if (isShuttingDown) return;
  const applicationShutdown = prepareApplicationShutdown();

  forcedExitTimer = setTimeout(
    () => finishShutdown(exitCode),
    SHUTDOWN_GRACE_PERIOD_MS,
  );
  forcedExitTimer.unref?.();

  void applicationShutdown.finally(() => finishShutdown(exitCode));
}

function trackTaskAnalytics(value: unknown): void {
  void analyticsService?.trackTaskUpdate(value);
  const update = TaskUpdateSchema.safeParse(value);
  if (
    update.success &&
    taskNeedsMainWindow(update.data.snapshot) &&
    mainWindow &&
    !mainWindow.isDestroyed()
  ) {
    resetCompanionPresentation();
    revealWindow(mainWindow);
  }
}

function taskNeedsMainWindow(snapshot: TaskSnapshot): boolean {
  return (
    snapshot.pendingInteraction !== null ||
    snapshot.phase === 'blocked' ||
    snapshot.phase === 'completed' ||
    snapshot.phase === 'failed' ||
    snapshot.phase === 'cancelled'
  );
}

function configureMicrophonePermissions(trustedWindow: BrowserWindow): void {
  const rendererSession = trustedWindow.webContents.session;

  rendererSession.setPermissionCheckHandler(
    (webContents, permission, _requestingOrigin, details) =>
      webContents?.id === trustedWindow.webContents.id &&
      permission === 'media' &&
      details.isMainFrame &&
      details.mediaType === 'audio',
  );

  rendererSession.setPermissionRequestHandler(
    (webContents, permission, callback, details) => {
      const mediaTypes =
        permission === 'media' && 'mediaTypes' in details
          ? details.mediaTypes
          : undefined;
      const isTrustedAudioRequest =
        webContents.id === trustedWindow.webContents.id &&
        details.isMainFrame &&
        mediaTypes?.length === 1 &&
        mediaTypes[0] === 'audio';

      callback(isTrustedAudioRequest);
    },
  );
}

function configureDock(): void {
  const dock = app.dock;
  if (process.platform !== 'darwin' || !dock) return;

  void dock.show();
  dock.setIcon(runtimeAppIconPath());
}

function runtimeAppIconPath(): string {
  return app.isPackaged
    ? path.join(process.resourcesPath, 'trocode-app-icon.png')
    : path.join(app.getAppPath(), 'src', 'assets', 'trocode-app-icon.png');
}

function revealWindow(window: BrowserWindow): void {
  if (window.isMinimized()) window.restore();
  window.show();
  window.moveTop();
  window.focus();
}

function ensureGlobalVoiceShortcut(): void {
  if (unregisterGlobalVoiceShortcut) return;

  unregisterGlobalVoiceShortcut = registerGlobalVoiceShortcut({
    getTarget: () => mainWindow,
    platform: process.platform,
    registry: globalShortcut,
    watchForMacOSShortcut:
      process.platform === 'darwin'
        ? (listener) =>
            watchMacOSGlobalVoiceShortcut({
              executablePath: macOSVoiceShortcutHelperPath(),
              onEvent: listener,
            })
        : undefined,
  });
}

function ensureGlobalTaskCancelShortcut(): void {
  if (unregisterGlobalTaskCancelShortcut) return;

  unregisterGlobalTaskCancelShortcut = registerGlobalTaskCancelShortcut({
    cancelTask: (taskId) => {
      executionCoordinator.cancel({ taskId });
    },
    registry: globalShortcut,
    updates: taskRuntime,
  });
}

function ensureGlobalGuidanceShortcuts(): void {
  if (unregisterGlobalGuidanceShortcuts) return;

  unregisterGlobalGuidanceShortcuts = registerGlobalGuidanceShortcuts({
    controls: {
      back: (taskId) => executionCoordinator.previousGuidance(taskId),
      next: (taskId) => executionCoordinator.nextGuidance(taskId),
      togglePause: (taskId) => {
        executionCoordinator.toggleGuidancePause(taskId);
      },
    },
    registry: globalShortcut,
    updates: taskRuntime,
  });
}

function macOSVoiceShortcutHelperPath(): string {
  return app.isPackaged
    ? path.join(process.resourcesPath, MACOS_VOICE_SHORTCUT_HELPER_NAME)
    : path.join(
        app.getAppPath(),
        '.generated-native',
        MACOS_VOICE_SHORTCUT_HELPER_NAME,
      );
}

function macOSVisionOcrHelperPath(): string {
  return app.isPackaged
    ? path.join(process.resourcesPath, MACOS_VISION_OCR_HELPER_NAME)
    : path.join(
        app.getAppPath(),
        '.generated-native',
        MACOS_VISION_OCR_HELPER_NAME,
      );
}

function ensureBackgroundTray(): void {
  if (backgroundTray) return;

  const trayIcon = nativeImage
    .createFromPath(runtimeAppIconPath())
    .resize({ height: 18, width: 18 });
  backgroundTray = new Tray(trayIcon);
  backgroundTray.setToolTip('TroCode');
  backgroundTray.setContextMenu(
    Menu.buildFromTemplate([
      {
        click: () => {
          if (mainWindow && !mainWindow.isDestroyed()) {
            revealWindow(mainWindow);
            return;
          }
          createWindow();
        },
        label: 'Show TroCode',
      },
      { type: 'separator' },
      {
        click: () => beginShutdown(),
        label: 'Quit TroCode',
      },
    ]),
  );
  backgroundTray.on('double-click', () => {
    if (mainWindow && !mainWindow.isDestroyed()) revealWindow(mainWindow);
  });
}

const createWindow = (): void => {
  if (mainWindow && !mainWindow.isDestroyed()) {
    revealWindow(mainWindow);
    return;
  }

  const nextMainWindow = new BrowserWindow({
    backgroundColor: '#f3f3ef',
    height: 820,
    icon: runtimeAppIconPath(),
    minHeight: 680,
    minWidth: 960,
    show: false,
    title: 'TroCode',
    width: 1280,
    webPreferences: {
      backgroundThrottling: false,
      contextIsolation: true,
      nodeIntegration: false,
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      sandbox: true,
      webSecurity: true,
    },
  });
  mainWindow = nextMainWindow;
  configureMicrophonePermissions(nextMainWindow);
  removeMainWindowCloseBehavior?.();
  removeMainWindowCloseBehavior = keepWindowAliveForBackgroundVoice(
    nextMainWindow,
    { isShuttingDown: () => isShuttingDown },
  );

  unregisterIpcHandlers?.();
  unregisterIpcHandlers = registerIpcHandlers(nextMainWindow, {
    appPreferencesService,
    appUpdateService,
    authService,
    cuaService,
    executionCoordinator,
    membershipService,
    onAuthSignedIn: identifyAnalyticsUser,
    onAuthSignedOut: async () => {
      taskHistoryService.setCurrentOwner(null);
      await analyticsService?.resetUser();
    },
    openSystemPermissionSettings: async (permission) =>
      shell.openExternal(systemPermissionSettingsUrl(permission), {
        activate: true,
      }),
    recordVoiceTranscript: async (input) => {
      await analyticsService?.trackVoiceTranscript(input);
    },
    requestScreenRecordingAccess: registerScreenRecordingHost,
    taskRuntime,
    taskSubmissionService,
    taskHistoryService,
    updateCompanionState,
    voiceService,
  });

  if (!app.isPackaged) {
    nextMainWindow.webContents.on('console-message', (details) => {
      if (!details.message.startsWith('[voice:renderer]')) return;
      console.info(details.message);
    });
  }

  nextMainWindow.once('ready-to-show', () => nextMainWindow.show());

  nextMainWindow.on('closed', () => {
    removeMainWindowCloseBehavior?.();
    removeMainWindowCloseBehavior = null;
    mainWindow = null;
    unregisterIpcHandlers?.();
    unregisterIpcHandlers = null;
  });

  nextMainWindow.webContents.setWindowOpenHandler(() => ({ action: 'deny' }));
  nextMainWindow.webContents.on('will-navigate', (event, navigationUrl) => {
    const entryUrl = new URL(MAIN_WINDOW_WEBPACK_ENTRY);
    const requestedUrl = new URL(navigationUrl);
    const isSameDevelopmentOrigin =
      !app.isPackaged && requestedUrl.origin === entryUrl.origin;
    const isPackagedApplication =
      app.isPackaged &&
      requestedUrl.protocol === 'file:' &&
      path.dirname(requestedUrl.pathname) === path.dirname(entryUrl.pathname);

    if (!isSameDevelopmentOrigin && !isPackagedApplication) {
      event.preventDefault();
    }
  });

  void nextMainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  if (!app.isPackaged) nextMainWindow.webContents.openDevTools({ mode: 'detach' });
};

function getCurrentCompanionScreenPosition(): Point {
  if (!companionWindow || companionWindow.isDestroyed()) {
    return { x: 0, y: 0 };
  }

  if (!shouldUseCompanionOverlay(process.platform)) {
    const [x = 0, y = 0] = companionWindow.getPosition();
    return { x, y };
  }

  const overlayBounds = getCompanionOverlayBounds();
  if (lastCompanionPosition) {
    return {
      x: overlayBounds.x + lastCompanionPosition.x,
      y: overlayBounds.y + lastCompanionPosition.y,
    };
  }

  const cursor = screen.getCursorScreenPoint();
  const display = screen.getDisplayNearestPoint(cursor);
  return placeCompanionNearCursor(
    cursor,
    display.bounds,
    COMPANION_SIZE,
    COMPANION_GAP,
  );
}

function applyCompanionScreenPosition(position: Point): void {
  if (!companionWindow || companionWindow.isDestroyed()) return;

  if (!shouldUseCompanionOverlay(process.platform)) {
    const [currentX, currentY] = companionWindow.getPosition();

    if (currentX !== position.x || currentY !== position.y) {
      companionWindow.setPosition(position.x, position.y, false);
    }
    return;
  }

  const overlayBounds = getCompanionOverlayBounds();
  if (overlayBounds.width <= 0 || overlayBounds.height <= 0) return;

  const currentBounds = companionWindow.getBounds();
  if (!boundsEqual(currentBounds, overlayBounds)) {
    companionWindow.setBounds(overlayBounds, false);
    lastCompanionPosition = null;
  }

  sendCompanionPosition({
    x: position.x - overlayBounds.x,
    y: position.y - overlayBounds.y,
  });
}

function positionCompanion(): void {
  if (!companionWindow || companionWindow.isDestroyed()) return;

  const glide = companionGlide;
  if (glide) {
    const progress =
      (Date.now() - glide.startedAt) / COMPANION_GLIDE_DURATION_MS;
    const position = interpolateCompanionPosition(glide.from, glide.to, progress);
    applyCompanionScreenPosition(position);
    if (progress >= 1) settleCompanionGlide();
    return;
  }

  if (companionPinnedPosition) {
    applyCompanionScreenPosition(companionPinnedPosition);
    return;
  }

  const cursor = screen.getCursorScreenPoint();
  const display = screen.getDisplayNearestPoint(cursor);
  applyCompanionScreenPosition(
    placeCompanionNearCursor(
      cursor,
      display.bounds,
      COMPANION_SIZE,
      COMPANION_GAP,
    ),
  );
}

const createCompanionWindow = (): void => {
  if (companionWindow && !companionWindow.isDestroyed()) return;

  const useOverlayCompanion = shouldUseCompanionOverlay(process.platform);
  const companionBounds = useOverlayCompanion
    ? getCompanionOverlayBounds()
    : { ...COMPANION_SIZE, x: 0, y: 0 };

  companionWindow = new BrowserWindow({
    alwaysOnTop: true,
    backgroundColor: '#00000000',
    focusable: false,
    frame: false,
    hasShadow: false,
    height: companionBounds.height,
    resizable: false,
    show: false,
    skipTaskbar: true,
    transparent: true,
    width: companionBounds.width,
    ...(useOverlayCompanion
      ? { x: companionBounds.x, y: companionBounds.y }
      : {}),
    webPreferences: {
      contextIsolation: true,
      nodeIntegration: false,
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      sandbox: true,
      webSecurity: true,
    },
  });

  companionWindow.setIgnoreMouseEvents(true, { forward: true });
  companionWindow.setVisibleOnAllWorkspaces(true, { visibleOnFullScreen: true });
  companionWindow.webContents.setWindowOpenHandler(() => ({ action: 'deny' }));
  companionWindow.webContents.on('did-finish-load', () => {
    sendCompanionState();
    lastCompanionPosition = null;
    positionCompanion();
  });
  companionWindow.webContents.on('will-navigate', (event) => {
    event.preventDefault();
  });

  const companionUrl = new URL(MAIN_WINDOW_WEBPACK_ENTRY);
  companionUrl.searchParams.set('mode', 'companion');
  companionUrl.searchParams.set(
    'tracking',
    useOverlayCompanion ? 'overlay' : 'native',
  );

  companionWindow.once('ready-to-show', () => {
    positionCompanion();
    companionWindow?.showInactive();
  });
  companionWindow.on('closed', () => {
    companionWindow = null;
    stopCompanionFollowing();
  });

  void companionWindow.loadURL(companionUrl.toString());
  positionCompanion();
  companionFollowTimer = setInterval(
    positionCompanion,
    COMPANION_FOLLOW_INTERVAL_MS,
  );
};

const createGuidanceWindow = (): void => {
  if (guidanceWindow && !guidanceWindow.isDestroyed()) return;

  guidanceWindow = new BrowserWindow({
    alwaysOnTop: true,
    backgroundColor: '#00000000',
    focusable: false,
    frame: false,
    hasShadow: false,
    height: GUIDANCE_CALLOUT_SIZE.height,
    resizable: false,
    show: false,
    skipTaskbar: true,
    transparent: true,
    width: GUIDANCE_CALLOUT_SIZE.width,
    webPreferences: {
      contextIsolation: true,
      nodeIntegration: false,
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      sandbox: true,
      webSecurity: true,
    },
  });

  guidanceWindow.setIgnoreMouseEvents(true, { forward: true });
  guidanceWindow.setVisibleOnAllWorkspaces(true, { visibleOnFullScreen: true });
  guidanceWindow.webContents.setWindowOpenHandler(() => ({ action: 'deny' }));
  guidanceWindow.webContents.on('did-finish-load', () => {
    sendCompanionGuidance();
    sendCompanionSpeech();
  });
  guidanceWindow.webContents.on('will-navigate', (event) => {
    event.preventDefault();
  });
  guidanceWindow.on('closed', () => {
    guidanceSpeechController?.abort();
    guidanceSpeechController = null;
    guidanceWindow = null;
    activeCompanionGuidance = null;
    activeCompanionSpeech = null;
  });

  const guidanceUrl = new URL(MAIN_WINDOW_WEBPACK_ENTRY);
  guidanceUrl.searchParams.set('mode', 'guidance');
  void guidanceWindow.loadURL(guidanceUrl.toString());
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
if (hasSingleInstanceLock) {
  void app.whenReady().then(async () => {
    configureDock();
    appUpdateService.start();
    analyticsService = new AnalyticsService({
      appVersion: app.getVersion(),
      architecture: process.arch,
      environment:
        process.env.POSTHOG_ENVIRONMENT?.trim() ||
        (app.isPackaged ? 'production' : 'development'),
      host: process.env.POSTHOG_HOST,
      identityStore: new FileAnalyticsIdentityStore(
        path.join(app.getPath('userData'), 'analytics-identity.json'),
      ),
      platform: process.platform,
      projectToken: process.env.POSTHOG_PROJECT_TOKEN,
    });
    taskRuntime.on('task-update', trackTaskAnalytics);

    await Promise.all([
      analyticsService.start(),
      cuaService.connectIfPermitted(),
      taskHistoryService.start(),
    ]);
    const authStatus = await authService.getStatus();
    if (authStatus.user) await identifyAnalyticsUser(authStatus.user);
    createWindow();
    createCompanionWindow();
    createGuidanceWindow();
    ensureBackgroundTray();
    ensureGlobalGuidanceShortcuts();
    ensureGlobalTaskCancelShortcut();
    ensureGlobalVoiceShortcut();
  });

  app.on('window-all-closed', () => {
    // The renderer is TroCode's background voice host. Explicit Quit remains
    // available from the application menu and tray.
  });

  app.on('activate', () => {
    if (isShuttingDown) return;
    // On OS X it's common to re-create a window in the app when the
    // dock icon is clicked and there are no other windows open.
    createWindow();
    createCompanionWindow();
    createGuidanceWindow();
  });

  const exitDevelopmentProcess = (): void => {
    beginShutdown();
  };

  process.on('SIGTERM', exitDevelopmentProcess);
  process.on('SIGINT', exitDevelopmentProcess);

  app.on('before-quit', (event) => {
    if (isShuttingDown) return;

    event.preventDefault();
    beginShutdown();
  });
}
