import { app, BrowserWindow, screen } from 'electron';
import path from 'node:path';

import { TaskRuntime } from './main/agent/task-runtime';
import { placeCompanionNearCursor } from './main/companion/companion-position';
import { CuaService } from './main/cua/cua-service';
import { registerIpcHandlers } from './main/ipc/register-ipc';
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
// eslint-disable-next-line @typescript-eslint/no-require-imports
if (require('electron-squirrel-startup')) {
  app.quit();
}

const taskRuntime = new TaskRuntime();
const cuaService = new CuaService();
const COMPANION_SIZE = { height: 58, width: 54 } as const;
const COMPANION_FOLLOW_INTERVAL_MS = 16;

let mainWindow: BrowserWindow | null = null;
let companionWindow: BrowserWindow | null = null;
let companionFollowTimer: ReturnType<typeof setInterval> | null = null;
let unregisterIpcHandlers: (() => void) | null = null;
let isShuttingDown = false;

function configureMicrophonePermissions(trustedWindow: BrowserWindow): void {
  const rendererSession = trustedWindow.webContents.session;

  rendererSession.setPermissionCheckHandler(
    (webContents, permission, _requestingOrigin, details) =>
      webContents?.id === trustedWindow.webContents.id &&
      permission === 'media' &&
      details.isMainFrame &&
      details.mediaType === 'audio',
  );

  rendererSession.setPermissionRequestHandler(
    (webContents, permission, callback, details) => {
      const mediaTypes =
        permission === 'media' && 'mediaTypes' in details
          ? details.mediaTypes
          : undefined;
      const isTrustedAudioRequest =
        webContents.id === trustedWindow.webContents.id &&
        details.isMainFrame &&
        mediaTypes?.length === 1 &&
        mediaTypes[0] === 'audio';

      callback(isTrustedAudioRequest);
    },
  );
}

const createWindow = (): void => {
  if (mainWindow && !mainWindow.isDestroyed()) {
    mainWindow.show();
    mainWindow.focus();
    return;
  }

  const nextMainWindow = new BrowserWindow({
    backgroundColor: '#0d1117',
    height: 820,
    minHeight: 680,
    minWidth: 960,
    show: false,
    title: 'TroCode',
    width: 1280,
    webPreferences: {
      contextIsolation: true,
      nodeIntegration: false,
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      sandbox: true,
      webSecurity: true,
    },
  });
  mainWindow = nextMainWindow;
  configureMicrophonePermissions(nextMainWindow);

  unregisterIpcHandlers?.();
  unregisterIpcHandlers = registerIpcHandlers(nextMainWindow, {
    cuaService,
    taskRuntime,
  });

  nextMainWindow.once('ready-to-show', () => nextMainWindow.show());

  nextMainWindow.on('closed', () => {
    mainWindow = null;
    unregisterIpcHandlers?.();
    unregisterIpcHandlers = null;

    if (process.platform !== 'darwin') app.quit();
  });

  nextMainWindow.webContents.setWindowOpenHandler(() => ({ action: 'deny' }));
  nextMainWindow.webContents.on('will-navigate', (event, navigationUrl) => {
    const entryUrl = new URL(MAIN_WINDOW_WEBPACK_ENTRY);
    const requestedUrl = new URL(navigationUrl);
    const isSameDevelopmentOrigin =
      !app.isPackaged && requestedUrl.origin === entryUrl.origin;
    const isPackagedApplication =
      app.isPackaged &&
      requestedUrl.protocol === 'file:' &&
      path.dirname(requestedUrl.pathname) === path.dirname(entryUrl.pathname);

    if (!isSameDevelopmentOrigin && !isPackagedApplication) {
      event.preventDefault();
    }
  });

  void nextMainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  if (!app.isPackaged) nextMainWindow.webContents.openDevTools({ mode: 'detach' });
};

const positionCompanion = (): void => {
  if (!companionWindow || companionWindow.isDestroyed()) return;

  const cursor = screen.getCursorScreenPoint();
  const display = screen.getDisplayNearestPoint(cursor);
  const position = placeCompanionNearCursor(
    cursor,
    display.bounds,
    COMPANION_SIZE,
  );
  const [currentX, currentY] = companionWindow.getPosition();

  if (currentX !== position.x || currentY !== position.y) {
    companionWindow.setPosition(position.x, position.y, false);
  }
};

const createCompanionWindow = (): void => {
  if (companionWindow && !companionWindow.isDestroyed()) return;

  companionWindow = new BrowserWindow({
    alwaysOnTop: true,
    backgroundColor: '#00000000',
    focusable: false,
    frame: false,
    hasShadow: false,
    height: COMPANION_SIZE.height,
    resizable: false,
    show: false,
    skipTaskbar: true,
    transparent: true,
    width: COMPANION_SIZE.width,
    webPreferences: {
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: true,
      webSecurity: true,
    },
  });

  companionWindow.setIgnoreMouseEvents(true, { forward: true });
  companionWindow.setVisibleOnAllWorkspaces(true, { visibleOnFullScreen: true });
  companionWindow.webContents.setWindowOpenHandler(() => ({ action: 'deny' }));
  companionWindow.webContents.on('will-navigate', (event) => {
    event.preventDefault();
  });

  const companionUrl = new URL(MAIN_WINDOW_WEBPACK_ENTRY);
  companionUrl.searchParams.set('mode', 'companion');

  companionWindow.once('ready-to-show', () => {
    positionCompanion();
    companionWindow?.showInactive();
  });
  companionWindow.on('closed', () => {
    companionWindow = null;
    if (companionFollowTimer) clearInterval(companionFollowTimer);
    companionFollowTimer = null;
  });

  void companionWindow.loadURL(companionUrl.toString());
  positionCompanion();
  companionFollowTimer = setInterval(
    positionCompanion,
    COMPANION_FOLLOW_INTERVAL_MS,
  );
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
void app.whenReady().then(() => {
  createWindow();
  createCompanionWindow();
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  createWindow();
  createCompanionWindow();
});

const exitDevelopmentProcess = (): void => {
  if (app.isPackaged) {
    app.quit();
    return;
  }

  if (isShuttingDown) return;
  isShuttingDown = true;
  if (companionFollowTimer) clearInterval(companionFollowTimer);
  companionFollowTimer = null;
  unregisterIpcHandlers?.();

  void cuaService.shutdown().finally(() => app.exit(0));
};

process.on('SIGTERM', exitDevelopmentProcess);
process.on('SIGINT', exitDevelopmentProcess);

app.on('before-quit', (event) => {
  if (isShuttingDown) return;

  event.preventDefault();
  isShuttingDown = true;
  if (companionFollowTimer) clearInterval(companionFollowTimer);
  companionFollowTimer = null;
  unregisterIpcHandlers?.();

  void cuaService.shutdown().finally(() => app.quit());
});
