import { useMemo, useState } from 'react';

import type { AppLanguage, KnowledgeSourceList, SaveKnowledgeActivityRequest } from '../shared/contracts';
import { randomUUID } from '../shared/renderer-uuid';

import { translate } from './app-language';

export function ActivityEditorPage({ appLanguage, sources, spaceId, onPublished }: { appLanguage: AppLanguage; sources: KnowledgeSourceList['items']; spaceId: string; onPublished: (versionId: string) => void }) {
  const [title, setTitle] = useState(''); const [objective, setObjective] = useState(''); const [instructions, setInstructions] = useState('');
  const [launchTarget, setLaunchTarget] = useState<'none'|'workspace'|'current_surface'>('none');
  const [hintMode, setHintMode] = useState<'direct'|'guided'|'socratic'>('guided');
  const [answerReveal, setAnswerReveal] = useState<'allowed'|'after_attempt'|'never'>('after_attempt');
  const [criteriaText, setCriteriaText] = useState('');
  const [requiresSubmission, setRequiresSubmission] = useState(false);
  const [selectedSources, setSelectedSources] = useState<string[]>([]); const [activityId, setActivityId] = useState<string | null>(null); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const clientId = useMemo(() => randomUUID(), []); const t = (message: string) => translate(appLanguage, message);
  const criteria = criteriaText.split(/\r?\n/u).map((line) => line.trim()).filter(Boolean).map((line) => { const [id = '', criterionTitle = '', description = '', tags = ''] = line.split('|').map((value) => value.trim()); return { id, title: criterionTitle, description, tags: tags.split(',').map((tag) => tag.trim()).filter(Boolean) }; });
  const definition: SaveKnowledgeActivityRequest['definition'] = { title, objective, instructions, launchTarget, guidancePolicy: { answerReveal, hintMode, maxHintLevel: 3 }, criteria, completionPolicy: { requiresSubmission, requiresFacilitatorConfirmation: false } };
  const save = async () => { setBusy(true); setError(null); try { const draft = await window.tro.saveKnowledgeActivity({ spaceId, clientId, definition, sourceVersionIds: selectedSources }); setActivityId(draft.id); setMessage(t('Draft saved.')); return draft.id; } catch (cause) { setError(cause instanceof Error ? cause.message : t('Could not save this Activity.')); throw cause; } finally { setBusy(false); } };
  return <section className="space-panel" aria-labelledby="activity-editor-heading"><div className="section-heading-row"><div><p className="eyebrow">{t('Published, reusable work')}</p><h2 id="activity-editor-heading">{t('Activity editor')}</h2></div></div>
    <div className="activity-form-grid"><label>{t('Title')}<input maxLength={240} onChange={(e) => setTitle(e.target.value)} value={title} /></label><label>{t('Objective')}<input maxLength={4000} onChange={(e) => setObjective(e.target.value)} value={objective} /></label><label className="activity-form-wide">{t('Instructions')}<textarea maxLength={24000} onChange={(e) => setInstructions(e.target.value)} rows={8} value={instructions} /></label><label>{t('Work context')}<select onChange={(e) => setLaunchTarget(e.target.value as typeof launchTarget)} value={launchTarget}><option value="none">{t('Conversation only')}</option><option value="workspace">{t('Workspace folder')}</option><option value="current_surface">{t('Current screen')}</option></select></label><label>{t('Guidance style')}<select onChange={(event) => setHintMode(event.target.value as typeof hintMode)} value={hintMode}><option value="direct">{t('Direct')}</option><option value="guided">{t('Guided debugging')}</option><option value="socratic">{t('Socratic questions')}</option></select></label><label>{t('Answer reveal')}<select onChange={(event) => setAnswerReveal(event.target.value as typeof answerReveal)} value={answerReveal}><option value="allowed">{t('Allowed')}</option><option value="after_attempt">{t('After an attempt')}</option><option value="never">{t('Never')}</option></select></label><label className="activity-form-wide">{t('Observable criteria')}<textarea onChange={(event) => setCriteriaText(event.target.value)} placeholder={t('criterion-id | Title | Description | concept-tag')} rows={5} value={criteriaText} /></label><label><input checked={requiresSubmission} onChange={(event) => setRequiresSubmission(event.target.checked)} type="checkbox" />{t('Require an explicit file submission')}</label></div>
    <fieldset className="source-picker"><legend>{t('Pinned Library versions')}</legend>{sources.filter((source) => source.latestVersion?.state === 'ready').map((source) => <label key={source.id}><input checked={selectedSources.includes(source.latestVersion!.id)} onChange={(event) => setSelectedSources((current) => event.target.checked ? [...current, source.latestVersion!.id] : current.filter((id) => id !== source.latestVersion!.id))} type="checkbox" />{source.displayName}</label>)}</fieldset>
    <div className="knowledge-actions"><button disabled={busy || !title || !objective || !instructions} onClick={() => void save().catch(() => undefined)} type="button">{t('Save draft')}</button><button className="primary-button" disabled={busy || !title || !objective || !instructions} onClick={() => void (async () => { try { const id = activityId ?? await save(); const version = await window.tro.publishKnowledgeActivity({ spaceId, activityId: id, clientId: randomUUID() }); setMessage(t('Activity published.')); onPublished(version.id); } catch (cause) { setError(cause instanceof Error ? cause.message : t('Could not publish this Activity.')); } })()} type="button">{t('Publish immutable version')}</button></div>{message && <p aria-live="polite">{message}</p>}{error && <p className="form-error" role="alert">{error}</p>}
  </section>;
}
